name: GitHub Actions Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Scan Dockerfile
      uses: anchore/scan-action@v6
      with: 
        path: ./Dockerfile
          #fail-build: true
          #severity-cutoff: critical
 
    - name: Login to Dockerhub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build with Docker
      uses: docker/build-push-action@v6
      with: 
        context: .
        push: true
        tags: michaelaviram/java-app:latest

