name: GitHub Actions Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  id-token: write

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:

    - name: Fetch files
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Set up cosign
      uses: sigstore/cosign-installer@v3.8.1

    - name: Dockerfile scan
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: Dockerfile
        failure-threshold: error
 
    - name: Login to Dockerhub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build with Docker
      uses: docker/build-push-action@v6
      with: 
        context: .
        push: true
        tags: michaelaviram/java-app:latest

    - name: Sign Image
      run: |
       cosign generate-key-pair
       cosign sign --yes --key cosign.key michaelaviram/java-app:latest
       cosign verify --key cosign.pub michaelaviram/java-app:latest

